Exercise 1. Import the numpy package under the name np

In [3]:
import numpy as np

Exercise 2. Print the numpy version and the configuration

In [12]:
print(np.__version__)
np.show_config()

1.10.1
lapack_mkl_info:
    library_dirs = ['C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win']
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_rt', 'mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_rt']
    include_dirs = ['C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/include']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win']
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_rt']
    include_dirs = ['C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/include']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
openblas_lapack_info:
  NOT AVAILABLE
mkl_info:
    library_dirs = ['C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64_win']
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', '

Exercise 3. Create a null vector of size 10

In [9]:
vector = np.zeros(10)
print("vector =", vector)

vector = [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


Exercise 4. How to find the memory size of any array

In [40]:
n = 5
m = 4
array = np.zeros((n, m))
memory_size = array.size * array.itemsize
print(memory_size)

160


Exercise 5. How to get the documentation of the numpy add function from the command line

In [163]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR: File `'`Untitled1.py'` not found.


Exercise 6. Create a null vector of size 10 but the fifth value which is 1

In [41]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


Exercise 7. Create a vector with values ranging from 10 to 49 

In [42]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Exercise 8. Reverse a vector (first element becomes last)

In [45]:
vector = np.arange(10)
vector = vector[::-1]
print(vector)

[9 8 7 6 5 4 3 2 1 0]


Exercise 9. Create a 3x3 matrix with values ranging from 0 to 8

In [51]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Exercise 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [57]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


Exercise 11. Create a 3x3 identity matrix 

In [59]:
matrix = np.eye(3,3)
print(matrix)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Exercise 12. Create a 3x3x3 array with random values

In [63]:
array = np.random.random((3,3,3))
print(array)

[[[ 0.52978448  0.46536112  0.45696204]
  [ 0.68196214  0.22311467  0.02582572]
  [ 0.20962087  0.46567924  0.13202977]]

 [[ 0.65428284  0.50526454  0.38907903]
  [ 0.59494764  0.96959867  0.43507744]
  [ 0.33228548  0.4566528   0.1873683 ]]

 [[ 0.81724373  0.75291299  0.71986872]
  [ 0.70391846  0.79258659  0.7579953 ]
  [ 0.49165478  0.27450514  0.24505186]]]


Exercise 13. Create a 10x10 array with random values and find the minimum and maximum values

In [85]:
vector = np.random.random((10, 10))
print(vector)
print("minimum =", np.min(vector))
print("maximum =", np.max(vector))

[[ 0.32138606  0.8867891   0.15319591  0.42700828  0.79353151  0.50788477
   0.44991447  0.8125616   0.33886056  0.51004517]
 [ 0.93024229  0.03284995  0.65534889  0.47539313  0.10327121  0.72461764
   0.62268618  0.35731541  0.93920238  0.29380181]
 [ 0.16433927  0.7188725   0.13705018  0.88941153  0.33649041  0.61125708
   0.18038704  0.95439782  0.69331263  0.78356601]
 [ 0.3134127   0.89893627  0.92080363  0.30112063  0.89878198  0.14866484
   0.2326785   0.13577172  0.6083282   0.25571243]
 [ 0.09882479  0.87211941  0.02387032  0.0535204   0.73867523  0.50986203
   0.61263245  0.64397447  0.62903596  0.97563255]
 [ 0.73338173  0.62884731  0.2779841   0.37260843  0.64883869  0.05406331
   0.6678166   0.75901466  0.89842374  0.51390358]
 [ 0.25101027  0.5962985   0.43045881  0.4151679   0.44916348  0.92080967
   0.76107342  0.51110542  0.86939981  0.40411878]
 [ 0.441812    0.51736253  0.0883565   0.11263778  0.19277533  0.60284049
   0.08926552  0.63867906  0.20825185  0.82698696]


Exercise 14. Create a random vector of size 30 and find the mean value

In [87]:
vector = np.random.random(30)
print(vector)
mean_value = vector.mean()
print("mean value =", mean_value)

[ 0.093536    0.57836403  0.85544717  0.77529742  0.2038198   0.25178979
  0.64533631  0.09374719  0.43376818  0.64036648  0.39396879  0.34147753
  0.47955543  0.1705253   0.13171266  0.19403022  0.60268313  0.33536025
  0.66650515  0.01964469  0.60688706  0.35068216  0.72423918  0.50370253
  0.3649203   0.20265804  0.66041163  0.86069201  0.21418938  0.84774397]
mean value = 0.441435392796


Exercise 15. Create a 2d array with 1 on the border and 0 inside

In [91]:
m = 7
n = 9
array = np.ones((m, n))
array[1:-1,1:-1] = 0
print(array)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]


Exercise 16. How to add a border (filled with 0's) around an existing array?

In [109]:
array = np.ones((3,3))
print(array)
array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]]


Exercise 17. What is the result of the following expression? 

In [110]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan 
0.3 == 3 * 0.1

False

Exercise 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [122]:
print(np.diag(np.arange(4) + 1, k = -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Exercise 19. Create a 8x8 matrix and fill it with a checkerboard pattern 

In [137]:
array = np.zeros((5, 5))
array[1::2,::2] = 1
array[::2,1::2] = 1
print(array)


[[ 0.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  1.]
 [ 0.  1.  0.  1.  0.]
 [ 1.  0.  1.  0.  1.]
 [ 0.  1.  0.  1.  0.]]


Exercise 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [146]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


Exercise 21. Create a checkerboard 8x8 matrix using the tile function

In [153]:
matrix = np.tile( np.array([[2,3],[8,5]]), (3, 3))
print(matrix)

[[2 3 2 3 2 3]
 [8 5 8 5 8 5]
 [2 3 2 3 2 3]
 [8 5 8 5 8 5]
 [2 3 2 3 2 3]
 [8 5 8 5 8 5]]


Exercise 22. Normalize a 5x5 random matrix 

In [157]:
matrix = np.random.random((5, 5))
print(matrix)
min = np.min(matrix)
max = np.max(matrix)
matrix = (matrix - min)/(max - min)
print(matrix)

[[ 0.61862277  0.53071902  0.52208789  0.96570038  0.6932133 ]
 [ 0.1552789   0.48949884  0.93947629  0.38489314  0.72778694]
 [ 0.56040627  0.06578259  0.53213123  0.35184368  0.64653248]
 [ 0.38063854  0.02103056  0.66242887  0.10127741  0.682675  ]
 [ 0.63094993  0.10598906  0.10686436  0.98550134  0.2063952 ]]
[[ 0.61960634  0.52846439  0.51951531  0.97946962  0.69694465]
 [ 0.13919379  0.48572574  0.95227948  0.37726657  0.73279191]
 [ 0.55924526  0.04640061  0.52992862  0.34299963  0.64854419]
 [ 0.37285524  0.          0.66502617  0.08320299  0.68601814]
 [ 0.63238761  0.08808821  0.08899575  1.          0.19219311]]


Exercise 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [160]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


Exercise 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [164]:
matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))
print(matrix1)
print(matrix2)
print(np.dot(matrix1, matrix2))

[[ 0.48083428  0.0691024   0.36450613]
 [ 0.55950369  0.22108321  0.01625461]
 [ 0.19833963  0.1517806   0.66858778]
 [ 0.14727603  0.83162809  0.49231874]
 [ 0.07374783  0.25678817  0.592125  ]]
[[ 0.88837959  0.1120491 ]
 [ 0.2775591   0.47406913]
 [ 0.90222516  0.54340219]]
[[ 0.77520996  0.28470979]
 [ 0.57308063  0.1763334 ]
 [ 0.82154568  0.45749033]
 [ 0.80584532  0.67827843]
 [ 0.67102003  0.45176074]]


Exercise 25. Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [169]:
vector = np.arange(10)
vector[3:9] *= -1
print(vector)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


Exercise 26. What is the output of the following script?

In [181]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


9 10


Exercise 27. Consider an integer vector Z, which of these expressions are legal? 

In [193]:
Z = np.ones(3)
print(Z**Z)
#2 << Z >> 2  non legal
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#Z<Z>Z  non legal

[ 1.  1.  1.]
[False False False]
[ 0.+1.j  0.+1.j  0.+1.j]
[ 0.08333333  0.08333333  0.08333333]


Exercise 28. What are the result of the following expressions?

In [195]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -2.14748365e+09]


C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':
C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  from ipykernel import kernelapp as app


Exercise 29. How to round away from zero a float array ? 